function [base_x, base_y, base_z, wobj_x, wobj_y, wobj_z] = importerFunction(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [BASE_X, BASE_Y, BASE_Z, WOBJ_X, WOBJ_Y, WOBJ_Z] =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [BASE_X, BASE_Y, BASE_Z, WOBJ_X, WOBJ_Y, WOBJ_Z] = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [base_x, base_y, base_z, wobj_x, wobj_y, wobj_z] = importfile("C:\OneDriveUCO\OneDrive - Universidad de Córdoba\02 Plantilla_2020_2021\Investigación\Artículos\2_RFID_Fardos\2_Código\1_CódigoABB\experimentos\prmario_COMPLETO_250_TAG32.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jul-2022 15:01:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [",", "[", "]"];

% Specify column names and types
opts.VariableNames = ["Var1", "base_x", "base_y", "base_z", "Var5", "wobj_x", "wobj_y", "wobj_z"];
opts.SelectedVariableNames = ["base_x", "base_y", "base_z", "wobj_x", "wobj_y", "wobj_z"];
opts.VariableTypes = ["string", "double", "double", "double", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var5"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["base_x", "base_y", "base_z", "wobj_x", "wobj_y", "wobj_z"], "FillValue", 0);
opts = setvaropts(opts, ["base_x", "base_y", "base_z", "wobj_x", "wobj_y", "wobj_z"], "ThousandsSeparator", ",");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
base_x = tbl.base_x;
base_y = tbl.base_y;
base_z = tbl.base_z;
wobj_x = tbl.wobj_x;
wobj_y = tbl.wobj_y;
wobj_z = tbl.wobj_z;
end